name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # 当推送 tag 时，会生成对应版本镜像

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 启用 QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 4. 启用 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5. 安装 yq（解析 docker-compose.yaml）
      - name: Install yq
        run: sudo apt-get install -y jq
      
      # 6. 检查 Docker 版本和配置
      - name: Check Docker version
        run: docker version

      # 7. 输出 Docker 相关信息
      - name: Check Docker info
        run: docker info

      # 8. 解析服务并构建
      - name: Build and Push Multi-Arch Images
        run: |
          set -e
          services=$(yq -o=json '.services' docker-compose.yaml | jq -r 'to_entries[] | select(.value.build) | .key')

          for service in $services; do
            context=$(yq -o=json ".services.$service.build.context" docker-compose.yaml | jq -r '.')
            image=$(yq -o=json ".services.$service.image" docker-compose.yaml | jq -r '.')

            echo "Building service: $service"
            echo "Context: $context"
            echo "Image: $image"

            TAGS="--tag ${image}:latest --tag ${image}:${GITHUB_SHA}"
            if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
              VERSION_TAG="${GITHUB_REF_NAME}"
              TAGS="$TAGS --tag ${image}:${VERSION_TAG}"
            fi

            # Build with limited parallelism to reduce memory usage
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --push \
              --file ${context}/Dockerfile \
              ${TAGS} \
              ${context} \
              --cache-from=type=registry,ref=${image}:cache \
              --cache-to=type=registry,ref=${image}:cache,mode=max \
              --parallel 1  # Limit parallelism
          done