name: Build and Push Multi-Arch Docker Images

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  # Matrix: 每个 Job 构建一个服务的一个架构
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [web, daily-hot, celery-worker, api]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 仅在 arm64 构建时设置 QEMU
      - name: Set up QEMU for arm64
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3

      - name: Clean Docker builder cache
        run: docker builder prune -af

      - name: Check disk before build
        run: |
          echo "===== Disk Usage ====="
          df -h

          echo "===== Docker Disk Usage ====="
          docker system df -v || true

          echo "===== Docker Images ====="
          docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}" || true

      # 构建单架构镜像（使用传统 docker build）
      - name: Build and Push ${{ matrix.service }} (${{ matrix.arch }})
        run: |
          docker build \
            --rm \
            --squash \
            --platform ${{ matrix.arch }} \
            -f ${{ matrix.service }}/Dockerfile \
            -t revornix/${{ matrix.service }}:${{ matrix.arch }}-${{ github.sha }} \
            ${{ matrix.service }}

          docker push revornix/${{ matrix.service }}:${{ matrix.arch }}-${{ github.sha }}

      - name: Check disk after build
        run: |
          echo "===== Disk Usage ====="
          df -h

          echo "===== Docker Disk Usage ====="
          docker system df -v || true

          echo "===== Docker Images ====="
          docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}" || true
      
      # 7. 删除本地镜像，释放空间
      - name: Remove local image to free space
        run: |
          docker rmi revornix/${{ matrix.service }}:${{ matrix.arch }}-${{ github.sha }} || true
          docker builder prune -af

  # 合并多架构 manifest（每个服务一个）
  merge:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service: [web, daily-hot, celery-worker, api]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Clean Docker builder cache
        run: docker builder prune -af

      # 创建并推送 manifest
      - name: Create and Push Multi-Arch Manifest for ${{ matrix.service }}
        run: |
          # latest 和 commit hash
          docker manifest create revornix/${{ matrix.service }}:latest \
            --amend revornix/${{ matrix.service }}:amd64-${{ github.sha }} \
            --amend revornix/${{ matrix.service }}:arm64-${{ github.sha }}

          docker manifest push revornix/${{ matrix.service }}:latest

          # 如果是 tag，创建额外 tag
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION_TAG="${GITHUB_REF_NAME}"
            docker manifest create revornix/${{ matrix.service }}:${VERSION_TAG} \
              --amend revornix/${{ matrix.service }}:amd64-${{ github.sha }} \
              --amend revornix/${{ matrix.service }}:arm64-${{ github.sha }}
            docker manifest push revornix/${{ matrix.service }}:${VERSION_TAG}
          fi